#pragma once
#include <string>
#include <unordered_set>

// Set of console folders where keeping the downloaded .zip AS-IS is acceptable/expected.
// For folders NOT in this set, we will unzip the archive and move the extracted contents instead.
static const std::unordered_set<std::string> ZIP_OK_FOLDERS = {
    "MAME2003PLUS",
    "MAME2010",
    "MAME",
    "FBNEO",
    "CPS1",
    "CPS2",
    "CPS3",
    "DAPHNE",
    "CPC",
    "ATARI800",
    "ATARI2600",
    "ATARI5200",
    "ATARI7800",
    "ATARIST",
    "COLECO",
    "C64",
    "AMIGA",
    "AMIGACD",
    "FAIRCHILD",
    "VECTREX",
    "ODYSSEY",
    "INTELLIVISION",
    "DOS",
    "SFX",
    "PC88",
    "PC98",
    "PCFX",
    "PCE",
    "N64",
    "FC",
    "SFC",
    "VB",
    "PANASONIC",
    "VIDEOPAC",
    "MD",
    "MS",
    "SG1000",
    "X1",
    "X68000",
    "ZXS",
    "NEOGEO",
    "NEOCD",
    "UZEBOX",
    "LYNX",
    "WS",
    "GW",
    "GB",
    "GBA",
    "GBC",
    "POKE",
    "GG",
    "NGP",
    "MEGADUCK",
    "SUPERVISION",
    "SUFAMI",
    "VMU",
    "PCECD",
    "FDS",
    "SATELLAVIEW",
    "SGB",
    "SEGA32X",
    "SEGACD",
    "MSX",
    "EASYRPG",
    "OPENBOR",
    "PICO",
    "SCUMMVM",
    "TIC"
};

// Returns true if we should UNZIP (i.e. folder NOT in the keep-zip set)
inline bool shouldUnzipForFolder(const std::string& folder) { return ZIP_OK_FOLDERS.count(folder) == 0; }