#pragma once
#include <SDL2/SDL.h>

// Unified controller button codes
// Map BUTTON_* to SDL_CONTROLLER_BUTTON_* values
// Use these everywhere for controller input
enum ControllerButton {
    BUTTON_A = SDL_CONTROLLER_BUTTON_B,
    BUTTON_B = SDL_CONTROLLER_BUTTON_A,
    BUTTON_X = SDL_CONTROLLER_BUTTON_Y,
    BUTTON_Y = SDL_CONTROLLER_BUTTON_X,
    BUTTON_DPAD_UP = SDL_CONTROLLER_BUTTON_DPAD_UP,
    BUTTON_DPAD_DOWN = SDL_CONTROLLER_BUTTON_DPAD_DOWN,
    BUTTON_DPAD_LEFT = SDL_CONTROLLER_BUTTON_DPAD_LEFT,
    BUTTON_DPAD_RIGHT = SDL_CONTROLLER_BUTTON_DPAD_RIGHT,
    BUTTON_LEFTSHOULDER = SDL_CONTROLLER_BUTTON_LEFTSHOULDER,
    BUTTON_RIGHTSHOULDER = SDL_CONTROLLER_BUTTON_RIGHTSHOULDER
};
